service_1:

  action_1:
    name: an.exchange.name
    type: fanout
    durable: true
    auto_delete: false
    arguments:
      one: 1
      two: second

  action_2:
    name: the.name


service_2:

  action_1:
    name: another
    type: topic
